### ISSUE TITLE
Initials don't show up on PersonView

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Graph-Controls#10]
## Describe the bug

- [x] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
1. Go to Sample
2. Click on Login
3. Enter user in PeoplePicker that doesn't have an image (like MyAnalytics on demo tenant)
4. See default image of user still

## Expected behavior
Default user should be for loading and signed-out states only.  Should see Initials if we have any details but no picture.

## Screenshots

![image](https://user-images.githubusercontent.com/24302614/65240577-94144880-daaf-11e9-8212-2af569af2772.png)

**Comment by michael-hawker** [comment]
Thinking more that we should use [PersonPicture](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.personpicture) for this; however, it's not supported by Uno yet.

@jeromelaban after we've got everything re-synced, let's chat quick about the PersonPicture control and what the gap left is.

**Comment by shweaver-MSFT** [comment]
I have fixed the issue with initials not rendering, but I did not implement the PersonPicture control. I think there is some amount of work to adapt the PersonPicture control template to support multiple lines of person metadata. So it may not be just a straight forward drop in place kind of thing.
