### ISSUE TITLE
Error related to "https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-MainLatest/nuget/v3/index.json"

### ISSUE THREAD

**Issue by zipswich** [CommunityToolkit/Graph-Controls#137]
This is probably related to #102. Since I am unable to comment there, I am asking the question here.
I updated VS 16.10.4 earlier. I am getting the following error when I try to update NuGet packages:

> Attempting to gather dependency information for package 'Uno.UI.3.9.1' with respect to project 'UtilityDesktop', targeting '.NETFramework,Version=v4.6.1'
> Unable to load the service index for source https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-MainLatest/nuget/v3/index.json.
>   Response status code does not indicate success: 401 (Unauthorized).

I can access "https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-MainLatest/nuget/v3/index.json" with the same Microsoft credential that I use in VS.  Is this a VS issue?  Does anyone else have the same issue with "https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-MainLatest/nuget/v3/index.json"?

**Comment by azchohfi** [comment]
This is pointing to the old **Windows**CommunityToolkit feed. That feed was renamed since the org name has changed.
Just rename the feed, removing the word Windows from it.
Btw, is this the latest commit from the main branch? It has already been fixed in another PR:
https://github.com/CommunityToolkit/Graph-Controls/blob/main/nuget.config#L6
Maybe you are just missing a git pull?

**Comment by shweaver-MSFT** [comment]
The dev branch was missing this, but I updated it earlier today. Both branches should be in good shape now.

**Comment by zipswich** [comment]
Thank you all for the help.   I am using "https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json" as suggested, and all problems are gone.

**Comment by zipswich** [comment]
Thank you all for the help. I am using "https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json" as suggested, and all problems are gone.
