### ISSUE TITLE
[Feature] Adding DecodePixelWidth/DecodePixelHeight to PersonView improve the rendering of user photos

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Graph-Controls#28]
## Describe the problem this feature would solve
When using the smaller version of the PersonView the photo becomes pretty ugly. I think this has to do with the fact that the actual image is way bigger and gets resized. This can be 'fixed' by setting the right DecodePixelWidth and DecodePixelHeight of the user picture. This should also improve the performance.

## Describe the solution
Create a property that sets the DecodePixelWidth/DecodePixelHeight for the user photo (more info here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage.decodepixelwidth)

## Describe alternatives you've considered
...

## Additional context & Screenshots
![image](https://user-images.githubusercontent.com/9866362/69960231-39fd1e00-1509-11ea-9c0f-f08fb9d1424c.png)

**Comment by michael-hawker** [comment]
Thanks for reporting the issue @niels9001. I wonder if we can do this a bit automatically based on the layout?  I'm also thinking of switching over to the `PersonPicture` control internally, so that may help as well?
