### ISSUE TITLE
PersonView still visible after logout

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Graph-Controls#6]
## Describe the bug
Same issue as https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/142

I tried fixing in similar manner; however, then the Login control's PersonView wasn't working right, very strange.

## Steps to Reproduce
1. Login to SampleTest app
2. Logout
3. Note user image is erased, but details remain.

## Expected behavior
All info should be gone.

## Environment

```
NuGet Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

**Comment by Kyaa-dost** [comment]
I am consistently seeing the same behavior after testing various times. In my case, the image and data both happened to be there. 

![image](https://user-images.githubusercontent.com/35208324/65264105-bd8a9f80-dac2-11e9-9606-4109acac902b.png)

**Comment by michael-hawker** [comment]
Thanks @Kyaa-dost, I had a similar fix that the graph toolkit had in the C# as most of the code is very similar; however, in our case here it introduced another bug, so I decided to log the issue here as a start.
